server: 
  port: 9001
spring: 
  application:  
    name: com.gcanfj-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_recruit?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: tiger
  jpa: 
    database: MySQL
    show-sql: true
