server:
  port: 9001
spring:
  application:
    name: bald-base
  datasource:
    username: root
    password: tiger
    url: jdbc:mysql://localhost:3306/tensquare_base
  jpa:
    database: mysql
    show-sql: true